/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export enum SyntaxMarkupType {
    KEYWORD = 'KEYWORD',
    COMMENT = 'COMMENT',
    NUM_LITERAL = 'NUM_LITERAL',
    STRING_LITERAL = 'STRING_LITERAL',
    DECLARATION = 'DECLARATION',
    PARAMETER_ASSIGNMENT = 'PARAMETER_ASSIGNMENT',
    IDENTIFIER = 'IDENTIFIER',
    IDENTIFIER_TYPE = 'IDENTIFIER_TYPE',
    IDENTIFIER_DECLARATION = 'IDENTIFIER_DECLARATION',
    ANNOTATION = 'ANNOTATION',
    PREPROCESSOR_ANNOTATION = 'PREPROCESSOR_ANNOTATION',
    PREPROCESSOR_MESSAGE = 'PREPROCESSOR_MESSAGE',
    HIGHLIGHT = 'HIGHLIGHT',
    SKIP = 'SKIP',
}